### ISSUE TITLE
Maquetación

### ISSUE THREAD

**Issue by omiras** [FOAP-Netmind-2021/avisa-me#10]
# Objetivo

Tener una maquetación inicial de toda la aplicación.

## Requisitos

1. Escribir en el fichero de [estilos](https://www.figma.com/file/IUGnIrSJ8RL1jdCuboNzWl/Avisa.me?node-id=203%3A2), todas las reglas CSS necesarias para definir los estilos para h1,h2,p,tipo de fuente (Robot); etc.
2. Escribir todos los colores de la aplicación en clases css . ejemplo: .primary { #F1F1F2}
3. Cambiar los iconos de las notas a los iconos bootstrap. Incluir todos los iconos, incluso de aquellas funcionalidades aun no implementadas
4. Adecuar el estilo de la nota, completadas y por completa, al protipo. Hacer boton derecho, copy/paste; para obtener el CSS
5. Añadir el logo a la parte superior derecha de la aplicaicón
6. Añadir el color de fondo del "header" de la aplicación
7. Añadir el menú vertical.
  1. Al pasar el ratón por encima de un item de menú, o al pulsar con el dedo, debe iluminarse con el color adecuado
  2. El primer item de menú, debe redirigir al usuario a /:idWorkspace
  3. El segundo item de menú, debe redirigir al usuairo a /:idWorkspace?type=reminder
  4. El tercer item de menú, deberia redirigir al usuario a /:idWorkspace?type=deleted
  5. El cuarto item de menú deberían ser unos "engranajes"; para llevar al usuario a la configuración de la aplicaición /settings/:idWorkspace
8. Solucionar los siguientes problemas visuales:

> Issue: Al hacer cllick en una tarea sin el cuerpo del texo, la experiencia de usuario no es la mejor...
Podemos pensar en otro control para gestionar el texto y dar mayor visibildad area de edición.

9. Cambiar el input del cuerpo del texto del formulario de añadir tarea, a un textarea
10. Mismo cambio para tareas activas y tareas ya completadas.

**Comment by ArielFabianN** [comment]
## Maquetación terminada
- Se ha abordado la UX mediante un proceso iterativo de mejora continua. El primer objetivo fue obtener un MVP, que se ha ido ampliando siguiendo las etapas básicas del proceso UX (investigación, estructura, bocetos y prototipado de alto nivel, pruebas y tests, aplicación del diseño en la UI).
- Se han seguido metodologías ágiles para la organización del trabajo diario, y se ha aplicado el Design Thinking para diseñar un producto que fuera deseable para el usuario.
- El prototipado se ha comenzado mediante un sketch inicial, que sirvió de base para realizar un wireframe completo en el que se basó el mockup, que una vez consensuado dió lugar al prototipo que se realizó con Figma.
- La UI (cabecera, íconos, menúes) fue estructurada a fin de poder transmitir eficazmente la lógica del diseño UX, mediante un lenguaje visual claramente identificativo.
- Se definieron los estilos, colores, fuentes, íconos y logo que serían utilizados como guía de estilo  durante el proyecto, buscando un estilo que fuera visualmente atractivo y coherente.
- Se han estructurado la CSS, las vistas y las áreas de trabajo para adecuarlas a la rearquitectura realizada, siguiendo el prototipo consensuado.
