### ISSUE TITLE
Como usuario, me gustaría mover a la papelera una nota

### ISSUE THREAD

**Issue by omiras** [FOAP-Netmind-2021/avisa-me#11]
# Objetvio

En la versión móvil, nos gustaría poder deslizar hacia la derecha una nota para enviarla a la papelera

## Funcionalidad
1. El usuario accede a un workspace
2. El usuario desliza una nota hacia la derecha (swipe right); y esta pasa al estado de "eliminada"

**Comment by cristian-cll** [comment]
## Realizado y testeado 
- Se ha creado la vista de papelera.
- Las notas se pueden enviar a la papelera mediante un conocido icono de "x".
- Se les añade a las instancias de taskModel, la propiedad boleana, "trashed".
- La papelera filtra todas las notas cuya propiedad "trashed" sea "true".
- Dentro de esta vista, el usuario podrá eliminar, individualmente, las notas o mediante un icono superior, vaciar toda la papelera. ![image](https://user-images.githubusercontent.com/78435266/127465600-002ad18c-1c31-4a55-b72b-b8e4854e6176.png)

- El icono que vacía la papelera solo aparecerá cuando existan notas.
![image](https://user-images.githubusercontent.com/78435266/127465681-c23fa4f4-24f1-491f-8655-2af09c63b4b9.png)

- Las notas renderizadas en la papelera, pierden cualquier detalle, color o recordatorio, exceptuando si éstas han sido completadas o no.
![image](https://user-images.githubusercontent.com/78435266/127465415-3acf0058-31a0-4143-ac7b-35aa1ca8f491.png)
- Añadida la posibilidad de recuperar de la papelera mediante el icono 
![image](https://user-images.githubusercontent.com/78435266/127465519-0756f983-8f10-421d-82c1-43c443eea40c.png)

- Un workspace ya no se muestra con las notas marcadas en papelera. Se filtran mediante un método estático "getUntrashedTasks" en el modelo workspaceModel. 

## Mejoras en un futuro: 
- El usuario desliza una nota hacia la derecha (swipe right); y esta pasa al estado de "eliminada"
