### ISSUE TITLE
Rearquitectura

### ISSUE THREAD

**Issue by omiras** [FOAP-Netmind-2021/avisa-me#12]
# Objetivo 

Queremos cambiar la manera de como gestionamos las tareas y los workspaces

## **Issues on 02/07/2021**

***

### <span style="color:red">**Problema#1**</span>
Cada vez que necesitamos una funcionalidad independiente del workspace, debemos llamar al workspace e iterar sobre sus propiedades y más tarde en estas.  
Esto supone un gran trozo de código difícil de leer más adelante.
En el caso que creciera, leer todo lo que conlleva un workspace, es mucho espacio en memoria y sale caro.

### <span style="color:green">**Solución #1**</span>
Cada funcionalidad que requiera de un constructor, con n instancias y sea independiente del contexto, debe ser guardada en su propio contenedor, colección.  
Tareas no depende del Workspace.
Estas funcionalidades harán referencia al workspace que pertenecen.

>Principio **Single Responsability SOLID**  
>El Workspace no debe conocer que tareas u otras funcionalidades pueda tener

- Crear colección para cada funcionalidad

***

### <span style="color:red">**Problema #2**</span>
Reutilizar la vista del index para el contexto del workspace, donde se muestra

- Poner en un módulo aparte las validaciones de express-validator
- Usar métodos 'static' de Mongoose para las funcionalidades existentes.

**Comment by omiras** [comment]
Cómo definir métodos estáticos: https://github.com/FOAP-NETMIND-PROMOCIO-2020/friendlyrent/blob/master/models/apartments.js

**Comment by cristian-cll** [comment]
- Se han separado los modelos "Task" y "Workspace"
- Se han añadido métodos estáticos y de instancia para que el modelo tenga más lógica en cuanto a las funcionalidades relacionadas
- Workspace e index tienen su propia página 
- Se ha modularizado express-validator
