### ISSUE TITLE
Como usuario, no debería poder crear tareas que tengan el texto de la tarea y el título vaciós a la vez.

### ISSUE THREAD

**Issue by omiras** [FOAP-Netmind-2021/avisa-me#13]
## Crear Tarea

1. Al crear una tarea, no debe ser posible crearla con titulo y cuerpo texto vacíos a la vez.
2. El botón de "Crear" debe estar oculto al principio.
3. En cuanto el usuario empieza a escribir en el campo del título o en el cuerpo del texto, hacer visible el botón
4. El botón debe volverse a ocultar cuando el usuario elimina completamente el texto en el título y en el cuerpo de texto

## Validación Mongoose

1. Crear una validación _custom_; la cual compruebe si estamos intentando crear una tarea cuyo titulo y cuerpo del texto son a la vez vacíos. [Enlace](https://mongoosejs.com/docs/validation.html)

## Validación en la vista
**Pasos para probar la issue:**
1.  Ir al menu inicial crear nueva nota. (localhost:3000)
2.  El usuario **NO** puede ver el botón 'Añadir nota'. El botón permanece oculto.
3.  Al iniciar la escritura en el campo 'Título' o en 'Añade una nota…', se muestra el botón  'Añadir nota'.
4.  El usuario puede añadir nueva nota de tres formas:
        Añadiendo un título y clicando botón Añadir nota.
        Añadiendo un texto y clicando botón Añadir nota.
        Añadiendo un título y un texto y clicando botón Añadir nota.
	
5.  El usuario **NO** puede crear una nota , si no tiene un título o un texto o le ha introducido sólo espacios en blanco.
6.  Al borrar el texto escrito de los campos  'Título' y 'Añade una nota….", desaparece el botón  'Añadir nota'.

## Validación en el controlador
**Pasos para probar la issue:**
1. Debemos hacer visible el botón de 'Añadir tarea'. Por lo que iremos al archivo views/partials/index.ejs y comentaremos en el input **id="createTask"**, el atributo **style="visibility: hidden"**.
2. Sin introducir caracteres o sólo introduciendo espacios en blanco.
3. Al clickar el botón de  'crear nota' debe saltar el error y la notaNO se creará.

## Validación en Mongoose
**Pasos para probar la issue:**
1. Se ha añadido al esquema taskSchema de mongoose un [Custom Validator](https://mongoosejs.com/docs/validation.html)
2. Primero, debemos hacer de nuevo visible el botón de 'Añadir tarea'. Por lo que iremos al archivo views/partials/index.ejs y comentaremos en el input **id="createTask"**, el atributo **style="visibility: hidden"**.
3. A continuación, tambien debemos comentar las restricciones implantadas en **/routes/index.js**. Concretamente las dos rutas que capturan el POST **taskValidator.emptyTask**.
4. Por último, al intentar crear la tarea vacia mongoose nos lanzará una excepción.

**Comment by omiras** [comment]
- Mover el JavaScript incrustado en el EJS a un fichero aparte.

**Comment by omiras** [comment]
**Idea test e2e:** 
- Voy a http://localhost:3000
- Empeiezo a escribir en el titulo de la tarea
- Borro el título de la tarea
- Tengo que comprobar que no está visible el botón de añadir nueva tarea.

**Comment by josecastp** [comment]
RESTRICCIÓN CREAR NOTA VACIA
    1. Ir al menu inicial crear nueva nota. (localhost:3000)
    2. El usuario no puede ver el botón 'Añadir nota'. El botón permanece oculto.
    3. Al iniciar la escritura en el campo 'Título' o en 'Añade una nota…', se muestra el botón  'Añadir nota'.
    4. El usuario puede añadir nueva nota de tres formas:
		1. Añadiendo un título y clicando botón Añadir nota.
		2. Añadiendo un testo y clicando botón Añadir nota.
		3. Añadiendo un título y un tetxto y clicando botón Añadir nota.
	
    5. El usuario NO puede crear una nota que almenos no tenga un título o un texto.
    6. Al borrar el texto escrito de los dos campos  'Título' y 'Añade una nota….", desaparece el botón  'Añadir nota'.

**Comment by Arnau-Mas** [comment]
### Bugs encontrados ###

* Me permite añadir notas vacías si le añado espacios (bar space)

**Comment by cristian-cll** [comment]
El botón de crear se encuentra oculto al mostrarse la página

Se han añadido 3 diferentes restricciones para evitar una nota totalmente en blanco

- Vista
Condición que oculta el botón si ambos campos, título y texto, están vacíos
- Controlador
Condición que muestra error si enviamos ambos campos, título y texto, vacíos
- Mongoose
Condición que rechza la entrada de datos si insertamos ambos campos, título y texto, vacíos

**Comment by josecastp** [comment]
Solucionado. Ver modificaciones en la nueva Issue https://github.com/FOAP-Netmind-2021/avisa-me/issues/31
