### ISSUE TITLE
Exportar notas

### ISSUE THREAD

**Issue by omiras** [FOAP-Netmind-2021/avisa-me#15]
# Objetivo

Queremos poder exportar todas las notas de la base de datos en diferentes formatos.

## Análisis

1. Buscar una biblioteca adecuada para poder exportar un conjunto de documentos de MongoDB a HTML, JSON, EXcel, CSV, etc... [Sugerencia](https://www.npmjs.com/package/export-from-json), pero buscar alternativas
2. En /settings, debe haber un botón (botones) para exportar **todas** las tareas a JSON, HTML,, etc... (decidir si boton unico o varios botones)
3. Crear nuevo endpoint /export/ , que reciba el tipo al que queremos exportar (json); y devuelve todas las tareas del workspace en dicho formato.
4. Investigar como "obligar" al navegador a que guarde el tipo de dato devuelto.

### Qué quiero poder exportar de mis notas ?

Exportar todos los campos de lod documentos MongoDB del workspace seleccionado.
Ejemplo: CSV

**id, title, text, finishedDate**
4543543545, traer pan, pero el pan bueno, 2021-08-01:13:00:00

 ## Exportación de tareas terminada
<ins>Pasos realizados en el desarrollo de la issue:</ins>
1. Se ha utilizado el modulo de terceros **export-from-json** para esta tarea.
2. A continuación, hemos añadido el formulario de exportación en **settings.ejs** y a continuación un nuevo endpoint /export/ que nos permita gestionar las solicitudes.
3. Seguidamente, en **public/js/settings.js** definimos la función que mostrará un botón 'Exportar' y el input 'nombre fichero', una vez se haya seleccionado un formato (de lo contrario, permanecerá oculto).
4. Nos hemos visto obligados a implementar un metodo  para reemplazar caracteres de _saltos de linea_ que aparecían al modificar una tarea creada con anterioridad.
5. Por último, a través de la función _exportTasks_ , implementada en el archivo settingControllers del controlador, nos exportará al formato deseado el **workSpace** en el cual estemos trabajando.

## Posibles mejoras futuras:
- Poder exportar a formato _.html_
- Mejorar la vista del formato _.txt_

**Comment by omiras** [comment]
@cristian-cll ha probado esta biblioteca y parece arrojar buenos resultados.

**Comment by omiras** [comment]
Prueba por favor la issue #7 

- Git clone
- ejecutar la app
- Probar los test que ha escrito el equipo de @Arnau-Mas @MohsinZamanShaheen

**Comment by omiras** [comment]
1. Porque se introducen tantos '\n' . Al modificar una nota es de tipo <p> con contenteditable. Se envía al servidor un texto con muchos saltos de línea.  
2. HTML si lo podéis solucionar durante del hoy, adelante.
3. Cuidad también la maquetación: recordad un prototipo para móvil y para versión escritorio.

**Comment by josecastp** [comment]
- Hemos testeado la issue y funciona correctamente.
- Se ha documentado el proceso de creación de la funcionalidad.

_Se da por finalizada esta tarea_
