### ISSUE TITLE
Colores de tareas

### ISSUE THREAD

**Issue by omiras** [FOAP-Netmind-2021/avisa-me#16]
# Objetivo 

Nos gustaría poder establecer un color a las tareas

<img src="https://oscarm.tinytake.com/media/10a6875?filename=1626354965478_TinyTake15-07-2021-03-15-49_637619517654003481.png&sub_type=thumbnail_preview&type=attachment&width=593&height=342" title="Powered by TinyTake Screen Capture"/><br><a href="https://www.tinytake.com">Powered by TinyTake Screen Capture</a>

## Análisis 

1. Establecer un icono para poder seleccionar el color al lado de la campanita (mirar los bootstrap icons)
2. Al hacer click encima, podemos seleccionar entre un conjunto de 8 colores. (basarse google keep!). Los 8 colores ofrecidos deben ser de un tono pastel para que la letra resalte y se vea bien.
3. Al seleccionar el color, se debe hacer un POST al servidor, para que dicha tarea sea a partir de ahora coloreada con el color elegido
4. Hay que modificar el modelo de tarea ! Nuevo campo: color: string (rgb(244,244,244))
5. Tener en cuenta validaciones express-validtor y de modelo.
5. **Opcionalmente**: poner etiquetas a los colores en la pagina de settings (preguntar Oscar o ver video del 14 de julio!)

## Pasos para testear la issue

##Crear nuevo Workspace 

1.Ir al endpoint http://localhost:3000. Se renderiza una vista en la cual debe verse una casilla donde el usuario puede escribir una nueva nota.
2.Crear nueva/as nota/s. El usuario escribe el título y/o texto de la nota. (Repetir el proceso varias veces)
3. En la nota creada, el usuario verá un icono para cambiar el color de fondo de la taréa.(No hace falta clicar al ícono, con pasar por encima ya funciona).
4. Una vez se ve el menú con los colores, el usuario clica al color deseado y el color de fondo de la nota pasa al color escojido.
5. El usuario puede cambiar el color de la misma nota las veces que quiera.
6. El usuario puede refrescar la página para comprobar que cada nota mantiene con el color escojido.

**Comment by cristian-cll** [comment]
Mohsin y Qamar terminaron esta issue y se testeó su funcionamiento.

- Utilizaron el icono de paleta de colores, en un tono colorido, que sugiere la acción perfectamente.
- Crearon el endpoint "/updateTaskColores" y mediante fetching, establecen en la base de datos, el color de manera persistente
- Ahora el modelo "taskModel" tiene la propiedad "color".
- En la versión móvil es igual de sencilla y accesible su funcionalidad.
- Por motivos de UX, el desplegable es hacía adentro de la nota, puesto que ya no nos encontramos en modo de edición de la misma (editar texto) y evitamos un posible corte con el scroll o limitación de pantalla en según que agente de usuario.

![image](https://user-images.githubusercontent.com/78435266/127459280-31cd2835-bbbe-4831-85a4-f9b4a83972ce.png)
