### ISSUE TITLE
Registro y login

### ISSUE THREAD

**Issue by omiras** [FOAP-Netmind-2021/avisa-me#17]
# Objetivo

Queremos poder registrarnos en la aplicación, hacer login y "reclamar" el workspace en el que estamos trabajando

## Análisis y diseño

Echar un vistazo a este [proyecto](https://github.com/junghwayang/task-api)
También valorar usar Passport
Incluso esta que es muy [sencilla](https://www.npmjs.com/package/basic-auth)

1. Habilitar botones de login y signup 
2. Al hacer click en dichos botones, vamos siempre a vistas diferentes.
2. Signup
    1. El usuario puede registrarse con correo y contraseña
    2.. Comprobar si el usuario ya existe en la base 
3. Login
    1. El usuario puede introducir usuario y contraseña para login
    2. Realizar la autentificación. Si es exitosa, se mantiene la sesión
    3. Se debe habilitar un botón de Logout
    4. Opción de recuperar contraseña (mirar modulo nodemailer)
 
## Qué puede hacer un usuario autentificado?
1. Si había creado un workspace, y se registra, pasa a su propiedad automaticamente (claim!) (opcional)
2. Puede crear nuevos workspaces y pasan a ser de su propiedad. Los workspaces deben poderse identificar con un nombre corto.
3. Todos los workspaces creados con la sesión iniciada son privados
4. Debo poder accede a mi lista de workspaces. A la lista de workspaces se accede por un item de menú nuevo 
5. Deberemos crear un nuevo endpoint /workspaces/:idUser , <-- sugerencia
6. Las settings debe seguir siendo de cada workspace
7. En las settings, debemos poder seleccionar si el worspace es publico o privado (por defecto pirvado)

## Idea visual del desplegable de workspaces

1. Cuando el usuario ha iniciado sesión, desaparece el botón de login y el de signuo
2. En su lugar, aparece un icono que al hacer clic, desplegue un componente parecido a este:
<img src="https://oscarm.tinytake.com/media/10a49cf?filename=1626280284205_TinyTake14-07-2021-06-31-23_637618770861055065.png&sub_type=thumbnail_preview&type=attachment&width=328&height=524" title="Powered by TinyTake Screen Capture"/><br><a href="https://www.tinytake.com">Powered by TinyTake Screen Capture</a>
3. En dicho componente podemos seleccionar a qué Workspace cambiar o añadir nuevo workspace o hacer logout.
4. Limitar el número workspaces a una setting configurable del usuario (todo los usuarios empiezan con el plan Free, que son 3 workspaces como maximo)

## Opcional: usuario super admin

1. Pueden ver todos los workspaces de todos los usuarios
2. Estadisticas: numero de usuarios, numero de notas, cuantos workspaces hay, las veces que visitan la página... Buscar biblioteca de terceros para hacer gráficos!

**Comment by omiras** [comment]
Se pide grabar la implementación de esta issue!

**Comment by omiras** [comment]
Idea de[ pantalla de login](https://sheltered-refuge-60050.herokuapp.com/login)

**Comment by omiras** [comment]
Diferentes tipos de authenticación [JWT y sesiones.](https://dev.to/thecodearcher/what-really-is-the-difference-between-session-and-token-based-authentication-2o39)

**Comment by omiras** [comment]
1. El usuario solo puede reclamar el ultimo workspace que ha creado de forma anónima (registrarse)
2. Hay una referencia del esquema de usuario hacia un array de Workspaces. Un workspace puede tener una referencia a un documento del esquema User.

**Comment by cristian-cll** [comment]
## Hecho
- Login, logout y signup con passport y estrategias
- Encriptación y comparación de contraseña en la base de datos
- Notificaciones de error, éxito y notificación mediante connect-flash
- Perfil de usuario con datos de interés
- Role usuario
- Tipo de cuenta Free y limitación correspondiente
- Validaciones varias en los controladores y alguna en el modelo de mongoose
- Recuperación de contraseña mediante link al correo y token con expiración
- Implementado nodemailer
- Uso de un email template
- Nuevas clase "Suscripción"
- Nuevos metodos en las clases que facilitan el acceso a la información
- Uso de cookie para localizar el workspace creado sin estar autenticado
- Estrategia para quedarse este workspace mediante login o registro
- Restructuración en la creación y renderizado de un workspace
- Un workspace se vuelve por defecto privado al añadirlo a cuenta de usuario
- Editar nombre y eliminación de un workspace
- Eliminación tareas del workspace eliminado
- Página de autenticación reusable para las tres funcionalidades
- Página de perfil
- Maquetación adaptada

**Comment by omiras** [comment]
Se ha implementado también la funcionalidad de eliminar notas
