### ISSUE TITLE
Establecer fecha de finalización

### ISSUE THREAD

**Issue by omiras** [FOAP-Netmind-2021/avisa-me#18]
# Objetivo

Poder establecer recordatorios sobre una tarea. Recibir avisos como por ejemplo un correo.

## Análisis

1. Todas las notas disponen de un icono para poder esteblecer una fecha de aviso
2. Al hacer clic sobre la campanita, aprece un selector de fecha y hora. ([Prototipo](https://www.figma.com/file/IUGnIrSJ8RL1jdCuboNzWl/Avisa.me?node-id=158%3A71))
3. Al establecer una fecha y hora para una tarea, debemos actualizar dicha tarea con una fecha de recordatorio
4. Modificar el modelo "tasks"; para añadir un nuevo campo del tipo Date; donde guardaremos la fecha y hora seleccionada

### Vista: tareas con recordatorio

1. En el menú lateral, existe un icono con forma de campanita
2. Al hacer click, mostraremos una vista, con las tareas ordenadas  por fecha de aviso más cercana. ([Prototipo](https://www.figma.com/file/IUGnIrSJ8RL1jdCuboNzWl/Avisa.me?node-id=158%3A396))
3. Además, para carea debe aparecer explícitamente la fecha de aviso.
4. La fecha de finalización siempre debería poderse cambiar al hacer click de nuevo en la campanita de la nota
5. ~~Colores: si la fecha de aviso es de menos de 8h, color rojizo.~~ Si ya ha pasado la fecha de aviso, que aparezca la fecha tachada (o cualquier idea similar!)  

### Enviar mail recordatorio
1. Cada cierto tiempo, la aplicación debe recuperar las tareas que tengan fecha de aviso no caducada de todos los usuarios registrados
2. Se enviará un correo de recordatorio a cada usuario si dispone de  una tarea con aviso que le falte menos de 8h para su caducidad. Solo una vez!! (seguramente modificar el modelo task para saber si ya hemos recordado una tarea)
3. Esta funcionalidad debería ejecutarse cada 5-10 minutos. Valorar si hacerlo en la misma aplicación Avisa.me o crear un script aparte.
4. Para el correo, mirar el modulo [nodemailer](https://www.npmjs.com/package/nodemailer).

**Comment by omiras** [comment]
Test de la issue #13 

- Git clone
- Ejecutar app
- Pasar de test de @josecastp @Qamar1806 
- Simplemente apuntar las cosas que no funcionan o que no entendeis; podeis también preguntar a los creadores de la issue.

**Comment by omiras** [comment]
@cristian-cll Pedir la implementación de nodemailer para la funcionalidad "Enviar mail recordatorio
"

**Comment by omiras** [comment]
## Email Recordatorio

1.  Implementa una ruta /enviar-notificaciones
2. Crear el controlador de estas notificaciones
3. Modificar modelo de tarea. Para indicar de que una tarea ya ha sido notificado por correo. Por defecto, vale false (o casi mejor, la fecha de notificación por correo, inicialmente null o undefined)
4. La función del controlador lo que hará es:
    1. Recuperar todas las tareas cuya fecha de finalización sea en menos de 8 h y no haya sido previamente notificada y tiene establecida fecha de aviso.
    2. Para cada tarea, ver que workspace tiene asociado
    3. Ver SI existe un usuario asociado al workspace
    4. Si tiene usuario asociado, recuperamos su email y hacemos el envío de correo
    5. Texto del email consensuarlo entre los dos

**Comment by ArielFabianN** [comment]
## Fecha de finalización implementada
- Se ha trabajado en una rama de desarrollo independiente de la principal, y una vez testada se ha fundido con la principal.
- A fin de poder incorporar las fechas de finalización en un formato particular se han modificado los controladores de las áreas de trabajo de usuario, y aquellos de las notas privadas y públicas. Tanto las que se encuentran en curso como aquellas cuya fecha ha pasado respecto de la fecha actual o se han marcado como completadas por el usuario.
- Se modificaron las vistas de usuario a fin de poder incorporar las fechas, y mostrarlas de diferente manera si se trata de una fecha anterior o una posterior a la fecha actual.
- Se estableció el almacenamiento de las mismas en una base de datos en la nube (MongoDB Atlas), así como el mecanismo necesario para que fueran recuperadas cuando la aplicación lo solicitase.
- Se ha incorporado la función de ordenar las notas por fecha de finalización.
- Se ha trabajado el envío de un email recordatorio utilizando Nodemailer, que es un paquete de distribución de NodeJS, teniendo en cuenta la fecha y hora de la nota respecto de la actual y si se trata de un usuario registrado.
- Se ha testado el uso correcto de las funcionalidades implementadas, durante el desarrollo e iteración y antes de su incorporación a la rama principal.
