### ISSUE TITLE
Crear notas

### ISSUE THREAD

**Issue by omiras** [FOAP-Netmind-2021/avisa-me#2]
## Funcionalidad

El usuario accede a la aplicación y puede crear una tarea

1. El usuario hace clic en la pantalla, en una zona de edición. Cuando carga la aplicación se produce un autofocus a esta zona de edición
2. El usuario escribe la tarea. 5000 carácteres límite
3. Cuando el usuario hace click fuera de la zona de edición, se guarda la tarea automáticamente
   1. Si hemos accedido en el directorio raiz de la App, se crea automaticamente una URL única. http://avisa.me/5858f-45454-3454d-45431
   2. MongoDB -> colección : urls? fj3j43j4jf. Un Array de TareaSchema -> un ID único a cada tarea.
   3. El servidor redigirige al usuario al endpoint http://avisa.me/5858f-45454-3454d-45431 donde va a poder ver las listas de tareas insertadas hasta el momento
4. Si el usuario estaba ya en una URL tipo http://avisa.me/5858f-45454-3454d-45431; se inserta la tarea en el espacio de trabajo identificado como '5858f-45454-3454d-45431'

modelo: urls
schemaUrls: {
   _id: '5858f-45454-3454d-45431',
   tareas: [TareasSchema]
]

TareaSchema
{
   texto: String, máximo de carácteres: 5000
}

¿Qué guardamos en una tarea?
 - Texto

Vamos a crear la estructura inicial de la aplicaicón con express-generator.
Eliminar las carpetas que no nos sirvan. Renombrar los ficheros para que tenga sentido respecto a nuestra app.
Documentar en README.MD como instalar nuestra aplicación.

**Comment by ignaciospadavecchia** [comment]
Hemos decidido añadir nodemon al proyecto.

**Comment by omiras** [comment]
@ignacio-spadavecchia Gracias !

**Comment by omiras** [comment]
1. ¿Creamos endpoints ya prefijados?
2. ¿Vamos a estar enviando las tareas creadas entre el cliente y el servidor , o se queda todo en el cliente?
  1. Las tareas se añaden manipuland el DOM desde el lado cliente (appendChild, textcontent,etc)
  2. Enviamos las tareas al servidor. El servidor las renderiza de vuelta en EJS
3. Aplicar una pseudo-metodología BEM para nombrar clases CSS
4. Poner en práctica el diseño mínimo para dar respuesta a la funcionalidad. No implementéis más allà de lo necesario para conseguir la tarea

**Comment by omiras** [comment]
Hay que dar de alta una instancia en Atlas MongoDB.  Creamos un correo "corporativo" para gestionar las credenciales de los servicios externos.

**Comment by omiras** [comment]
Usaremos bootstrap 5 para maquetar la aplicación

**Comment by omiras** [comment]
La creación de espacios se parece mucho a la funcionalidad implementada por paste.bin . [Video](https://oscarm.tinytake.com/tt/NTU2MjcyMF8xNzMyNzY3MQ)
Incluso te permite, si te registras, guardar tus "paste bin"!

**Comment by omiras** [comment]
Implementad también:


1. Validaciones posibles dentro del modelo de Mongoose. Campos requeridos, tamaño máximo del texto, etc. (maxlength, required, etc)
2. Validaciones en el formulario! (required, maxlength!)
3. Variables de entorno para configurar la conexión a la base de datos MongoDB Atlas

**Comment by cristian-cll** [comment]
Completado y testeado.

- Nuevo endpoints: POST  "/" crea la nota y  GET "/:idWorkspace" renderiza el workspace
- Se ha utilizado la misma codificación única de mongoDB para indentificar un objeto creado como dirección url del sitio a compartir/usar (el ObjectId).
- Se crean dos colecciones; workspaces (workspaceModel) y tasks (taskModel). 
- Cada instancia de taskModel, hace referencia al workspace que pertenece. Ésta también almacena un título de 140 car. máx. y un texto de cuerpo de 5000 car. máx. (totalmente orientativo).
- Validaciones de obligatoriedad y longitud de caracteres en la vista, mediante los atributos del formulario y en Mongoose a través del su schema.
- Se implementa express-validator y con ello, otra validación en el controlador.
- Se utiliza el modulo dotenv, y se establecen variables de entorno para garantizar datos privados de autenticación en la conexión de la base de datos.
