### ISSUE TITLE
Tecnologías usadas 

### ISSUE THREAD

**Issue by omiras** [FOAP-Netmind-2021/avisa-me#23]
1. Identificar todas las partes de la aplicación Web distribuida; y como se comunican las partes entre sí. Realizar un esquema parecido a los que aparecen en [estas imágenes.](https://user-images.githubusercontent.com/49642130/91548771-31196b80-e926-11ea-889d-3e9f2249c163.png)

2. Deberáían relacionarse los siguientes conceptos:

- Que papel tiene NodeJS/Express en la arquitectura. Importante nombres 'Express' porque es el framework que utilizamos.
- Que motor de plantillas hemos utilizado
- Que tecnologías hay en el lado cliente (HTML, CSS, Javascript, JQuery, Bootstrap, AJAX)
- Como se relaciona nuestra aplicación NodeJS con MongoDB (en que servidor se encuentra? En Atlas)
- Que biblioteca usamos para la autentificación
- Que aplicación utilizamos para enviar correos y como se comunica con NodeJS

3. Posibles mejoras de la arquitectura para el futuro
- Filtrar por IP las peticiones a la base de datos de MongoDB (no permitir que cualquiera pueda hacer peticiones)
- Implementar protocolo HTTPS para hacer las peticiones seguras a nuestra aplicación
- Externalizar el almacenamiento de imágenes en un servicio externo, como Amazon.
- Tareas de re factorización; como por ejemplo extender el modelo vista controlador a todas las partes de la aplicación

[Ejemplo](https://github.com/FOAP-NETMIND-PROMOCIO-2020/friendlyrent/wiki/Arquitectura-de-FriendlyRent)

**Comment by cristian-cll** [comment]
![ORGANIGRAMA](https://user-images.githubusercontent.com/78435266/126797167-0bce29e3-e8ba-4f89-b899-2f0f7e171684.png)

# Estructura de Avísame 

Diferenciar en las tecnologías empleadas en su estructura

###  Backend - Base de datos y servidor
---

<ins>Entorno de ejecución</ins>
- **NodeJS** 
_Nos permite tener una aplicación web o API, del lado servidor, usando JavaScript_

<ins>Marcos o frameworks utilizados</ins>

- **Express** 
_Dota de funcionalidades y minimalismo extra a NodeJS en cuanto a las aplicaciones web o API's_

<ins>Base de datos</ins>

<table>
    <thead>
        <tr>
            <th colspan=2>Detalles</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>Nombre</td>
            <td>MongoDB</td>
        </tr>
        <tr>
            <td>Sistema de base de datos:</td>
            <td>NoSQL</td>
        </tr>
        <tr>
            <td>Host</td>
            <td>Atlas</td>
        </tr>
        <tr>
            <td>Cliente MongoDB</td>
            <td>Mongoose</td>
        </tr>
    </tbody>
</table>

- **Mongoose** 
_Librería (ODM) utilizada para extender y minimizar las funcionalidades que podemos usar con MongoDB_


<ins>Motor de plantilla de renderizado html</ins>
- **EJS**
_Facilita la transmisión de datos, desde el servidor a la vista_

<ins>Otras librerías o módulos utilizados:</ins>

- **Passport**
_Autenticación y registro de usuarios mediante estrategias_

- **Jest/Puppeteer/Supertest**
_Implementación TDD en el proyecto. Test unitarios, de integración y end-to-end._

- **Nodemailer**
_Envío de correo electrónico mediante un servidor SMTP. Utilizado para recuperar contraseña usuario o informar que se acerca la fecha del recordatorio de una tarea._

- **exportFromJSON**  
_Exportación de datos a los diferentes formatos, text, css, html, json, csv, xls y xml._

- **Node Cron**  
_Programador de tareas en JS puro. Ejecuta scripts de forma programada._

### Frontend - Vista del usuario
---

- **Bootstrap** 
_Librería que simplifica el diseño y la adaptación del mismo para cualquier agente de usuario_

<ins>Lenguajes de programación, marcado y de estilo utilizados</ins>

- **JavaScript ES6** 
_Dinamismo al código estático HTML_

- **HTML5** 
_Estructural_

- **CSS3** 
_Estilos propios para el diseño de la app_

# Mejoras en un futuro

- Filtrar por IP las peticiones a la base de datos de MongoDB (no permitir que cualquiera pueda hacer peticiones)
- Implementar protocolo HTTPS para hacer las peticiones seguras a nuestra aplicación
- Refactorizar el código, usando un único layout principal y enquistar en él las demás vistas, reduciendo notablemente el código
