### ISSUE TITLE
Prototipo Figma

### ISSUE THREAD

**Issue by omiras** [FOAP-Netmind-2021/avisa-me#24]
1. Animar prototipo 
2. Que sirva para demostrar que se ha hecho un diseño con un programa profesional

**Comment by vcollazos** [comment]
https://user-images.githubusercontent.com/80645252/127365958-0db3a2fd-0df3-4dee-9858-55d0ca99429b.mp4

**Comment by vcollazos** [comment]
Después de la idea principal del proyecto a realizar, se ha trabajado conjuntamente en el desarrollo de la aplicación,
inicialmente en el prototipo de la misma.
Hemos consensuado en equipo, la creación del logotipo, colores, tipografía y el mínimo detalle para la aplicación.
Siempre respetando los estándares del UX/UI para la satisfacción y el agrado del usuario.

Al crear primeramente el prototipo, teniendo en cuenta, medidas, distancias, etc... para los diferentes dispositivos donde la app pudiera ser usada, nos hemos basado en un diseño y desarrollo responsive y sencillo para su usabilidad.
