### ISSUE TITLE
Esquema de base de datos

### ISSUE THREAD

**Issue by omiras** [FOAP-Netmind-2021/avisa-me#25]
Siguiendo este [ejemplo](https://github.com/FOAP-NETMIND-PROMOCIO-2020/friendlyrent/wiki/Esquema-de-datos-de-la-aplicaci%C3%B3n) hacer un esquema de la base de datos, explicando las partes más relevantes

Aparte, dibujar el esquema con el siguiente programa: [Moon Modeler](https://www.datensen.com/data-modeling/moon-modeler-for-databases.html)

**Comment by ArielFabianN** [comment]
### Esquema de la aplicación

La aplicación permite crear espacios de trabajo que contienen notas editables y personalizables que se pueden compartir y gestionar de forma colaborativa. En el caso de los usuarios registrados, se ofrece la opción de privatizar estos espacios de trabajo.

Este esquema refleja de forma gráfica las colecciones de datos que la aplicación genera.

### Funcionalidades de usuarios:

* Crear un workspace y compartirlo mediante una URL única.
* Crear, editar y elminar notas.
* Marcar notas como completadas.
* Añadir una fecha de finalización.
* Registrarse en la aplicación.

### Funcionalidades de usuario registrado.

* Crear los workspaces privados.
* Tener acceso a los workspaces privados.
* Ver un resumen de la actividad realizada.
* Editar y eliminar nombres de los workspaces.
* Recuperar la contraseña.
* Cambiar la contraseña.
* Ampliar el número de workspaces disponibles mediante suscripción premium.

### La base de datos se compone de las siguientes colecciones:

users: :id, role, email, password, subscription, createdAt, updatedAt.
subscriptions: _id, account, limitWorkspace, workspaces [], user, createdAt, updatedAt.
workspaces: _id, name, settings {hideCompletedTask, visibility, _id}, tasks, createdAt, updatedAt, subscription.
tasks: _id, reminderNotification, title, text, workspace, createdAt, updatedAt, color, reminderDate, finishedDate, trashed.

<img width="800" alt="Captura" src="https://user-images.githubusercontent.com/79173115/126785229-7a484ec2-dd25-474b-a64f-8766a9cf2a4f.PNG">
