### ISSUE TITLE
Whiteboard animation

### ISSUE THREAD

**Issue by omiras** [FOAP-Netmind-2021/avisa-me#26]
Crear un _story board_ sobre

1. Contexto del equipo de trabajo (de donde venís, etc.)
2. Motivación de la creación de Avisa.me
3. Como funciona la app a grandes rasgos
4. Quizás comentar algún momento del desarrollo épico.

**Comment by cristian-cll** [comment]
Qamar y Mohsin se han encargado de hacer el vídeo del story board.
Han abordado los 3 temas más importantes señalados en la issue:
- Contexto del equipo de trabajo (de donde venís, etc.)
- Motivación de la creación de Avisa.me
- Como funciona la app a grandes rasgos


https://user-images.githubusercontent.com/80530839/127242060-3aad3520-f6eb-4056-a1fd-45fab455f593.mp4

**Comment by omiras** [comment]
Que buena la animación, muy bien!
