### ISSUE TITLE
No puedo copiar la URL desde el móvil

### ISSUE THREAD

**Issue by omiras** [FOAP-Netmind-2021/avisa-me#29]
#### Steps to reproduce the issue

1.  Ir a la versión móvil de la app
2.  Crear workspace anónimo
3.  Hacer click en copiar URL
4. Ir a Whatsapp. Intentar pegar la nota.

#### What's the expected result?

- Esperaba poder pegar la URL

#### What's the actual result?

- Whatsapp no detecta que haya nada que pegar

**Comment by omiras** [comment]
Rectifico, al hacer clic en el icono, si se copia la URL. Pero esperaba que también funcionara al hacer click en el texto

**Comment by cristian-cll** [comment]
Arreglado. Para mejorar la UX, se ha hecho enlace, tanto al icono como al texto de copiar URL y de detalles de un workspace.
