### ISSUE TITLE
Las notas coloreadas no se vuelven grises al ser completadas

### ISSUE THREAD

**Issue by omiras** [FOAP-Netmind-2021/avisa-me#30]
#### Steps to reproduce the issue

1.  Colorear una nota
2. Marcada como completada 

#### What's the expected result?

- Esperaria ver la nota en gris

#### What's the actual result?

- La nota sigue mostrándose en el color que estaba

**Comment by cristian-cll** [comment]
Arreglado! El componente card disabled manttenía el style inline del background.
