### ISSUE TITLE
Se pueden crear notas "vacías" si solamente insertamos espacios en blanco

### ISSUE THREAD

**Issue by cristian-cll** [FOAP-Netmind-2021/avisa-me#31]
### Bugs encontrados ###

* Me permite añadir notas vacías si le añado espacios (bar space)

_Originally posted by @Arnau-Mas in https://github.com/FOAP-Netmind-2021/avisa-me/issues/13#issuecomment-880749786_

Evitar que ambos campos, título y texto, de una nota contengan únicamente caracteres en blanco del espaciado

## Validación en la vista
**Pasos para probar la issue:**
1.  Ir al menu inicial crear nueva nota. (localhost:3000)
2.  El usuario **NO** puede ver el botón 'Añadir nota'. El botón permanece oculto.
3.  Al iniciar la escritura en el campo 'Título' o en 'Añade una nota…', se muestra el botón  'Añadir nota'.
4.  El usuario puede añadir nueva nota de tres formas:
        Añadiendo un título y clicando botón Añadir nota.
        Añadiendo un texto y clicando botón Añadir nota.
        Añadiendo un título y un texto y clicando botón Añadir nota.
	
5.  El usuario **NO** puede crear una nota , si no tiene un título o un texto o le ha introducido sólo espacios en blanco.
6.  Al borrar el texto escrito de los campos  'Título' y 'Añade una nota….", desaparece el botón  'Añadir nota'.

## Validación en el controlador
**Pasos para probar la issue:**
1. Debemos hacer visible el botón de 'Añadir tarea'. Por lo que iremos al archivo views/partials/index.ejs y comentaremos en el input **id="createTask"**, el atributo **style="visibility: hidden"**.
2. Sin introducir caracteres o sólo introduciendo espacios en blanco.
3. Al clickar el botón de  'crear nota' debe saltar el error y la notaNO se creará.

## Validación en Mongoose
**Pasos para probar la issue:**
1. Se ha añadido al esquema taskSchema de mongoose un [Custom Validator](https://mongoosejs.com/docs/validation.html)
2. Primero, debemos hacer de nuevo visible el botón de 'Añadir tarea'. Por lo que iremos al archivo views/partials/index.ejs y comentaremos en el input **id="createTask"**, el atributo **style="visibility: hidden"**.
3. A continuación, tambien debemos comentar las restricciones implantadas en **/routes/index.js**. Concretamente las dos rutas que capturan el POST **taskValidator.emptyTask**.
4. Por último, al intentar crear la tarea vacia mongoose nos lanzará una excepción.

## Pasos para solucionar el bud  **Crear tarea sólo con espacios en blanco**
1.  Se ha modificado el script del backend para que deba superar una expresión regular y hasta que no lo haga, no muestra el botón de crear tarea.
2.  Se ha añadido una función de validacion (validate) en Mongoose.
3.  Por último, también se ha creado un nuevo test de validación en el archivo task-Validator que actua en el controlador.

**Comment by josecastp** [comment]
Estoy yo en ello...

**Comment by cristian-cll** [comment]
Perfecto Jose, creas la rama con la issue?

**Comment by josecastp** [comment]
Ya esta la tarea terminada en la rama: No-solo-espacio-en-blanco
1. Se ha modificado el script del backend para que deba superar una expresión regular y hasta que no lo haga, no muestra el botón de crear tarea.
2. Se ha añadido una función de validacion (validate) en **Mongoose.**
3. Por último, también se ha creado un nuevo test de validación en el archivo task-Validator que actua en el controlador.

**Está testeada y funciona como se espera**. Permite crear la tarea una vez se ha añadido un caracter que NO sea espacio-s en blanco.
