### ISSUE TITLE
Subir Avisa.me a Heroku

### ISSUE THREAD

**Issue by omiras** [FOAP-Netmind-2021/avisa-me#4]
1. Darse de alta en heroku.app con el mail del proyecto
2. Subir la aplicación actualmente tal y como está, configurando adecuadamente las variables de entorno
3. Url: http://avisame.herokuapp.com ? Si estuviera cogido, buscar alternativa parecida (avisa-me, etc.)

**Comment by cristian-cll** [comment]
Hecho!
App subida a heroku y configuradas las variables de entorno.
https://avisame-app.herokuapp.com/
