### ISSUE TITLE
Marcar nota como finalizada

### ISSUE THREAD

**Issue by omiras** [FOAP-Netmind-2021/avisa-me#5]
# Objetivo y análisis

- Queremos poder marcar una nota como finalizada. Existirá un control que el usuario podrá clicar para efectuar esta acción [ver prototipo](https://www.figma.com/file/IUGnIrSJ8RL1jdCuboNzWl/Avisa.me?node-id=0%3A1). Es un símbolo de "check"
- Las notas finalizadas tendran un diseño diferente. Se sugiere que pierda algo de opacidad y se vea en color grisaceo 
- Añadir algun campo al modelo para poder marcar las notas como finalizadas. Por ejemplo, algo asi como fechaFinalizado, de tipo Date
- Hay que modificar la vista "Lista de tareas" para aplicar el diseño nuevo a las tareas finalizadas. 
  - En primer lugar, deben verse las tareas/notas que aún no se han finalizado
  - En segundo lugar, deben verse las tareas/notas finalizadas.
  - Para cada tarea, debemos renderizar o guardar en un atributo data- el ID de cada una de las tareas. Guardarlo en el DIV  <div style="border:1px solid black">
 - Al hacer clic en el icono de "check", pasará lo siguiente:
    1. El icono está encapsulado con un <a> cuyo href es "/tasks/:idTask/completed"
    2. Es necesario generar el endpoint "/tasks/:idTask/completed"; que se va a encargar de marcar la tarea 'idTask' como completada

# Maquetación
1. Añadir barra superior de color
2. Añadi el logo en parte superior derecha
3. Redondead las notas (aplicar un poco el diseño del prototipo)
4. Aplicar el tipo de fuente (familia)

# Pasos para probar la issue

MARCAR NOTA COMO FINALIZADA

1. Ir a un workspace con notas que aun resten por finalizar
2. Hacer click en el icono de "check" de una nota.
3. Dicha nota tiene que cambiar de color (gris) ; y situarse al final de las notas, junto a otras notas finalizadas. Además, tiene que desaparecer el icono de "check"

WORKSPACE NO TIENE NOTAS PARA FINALIZAR

1. Ir a un workspace con todas las notas finalizadas.
2. El usuario NO debe poder marcar como finalizada ninguna nota

CAMBIAR TAMAÑO DE LA VENTANA PERMITE SEGUIR MARCAR NOTAS

1. Ir a un workspace con notas para finalizar
2. El usuario cambia la resolución de la ventana
3. El usuario puede seguir haciendo "check" en todas las notas

**Comment by cristian-cll** [comment]
## Realizada  y testeada la issue.
- Es posible marcar  como finalizada una tarea/nota mediante un icono "check".
- Se ha creado el endpoint "tasks/:idTask/completed'
- Una vez marcada, se establecerá  en la propiedad "finishedDate" del modelo taskModel, la fecha en la que se realiza la acción.
- La nota finalizada o completada, tiene un diseño más apagado, grisáceo, perdiendo cualquier detalle como , recordatorio, color o color de fondo.
- La nota marcada, por ahora es permanente y no acepta ningún tipo de cambio.

![image](https://user-images.githubusercontent.com/78435266/127461273-1ca99de7-91bf-4135-9df1-259cbd02a268.png)

## Nuevas funcionalidades 
- Se ha añadido la función de recuperar la tarea, desmarcarla de completada.
- Una vez recuperada, ésta mantiene todas sus propiedades iniciales.
- Se filtra en el workspace mediante la opción de ocultar o mostrar las tareas completadas.
