### ISSUE TITLE
Modificar tarea

### ISSUE THREAD

**Issue by omiras** [FOAP-Netmind-2021/avisa-me#6]
# Objetivo y Análisis

Un usuario puede modificar el texto y título de una tarea.
1. El usuario hace clic en una nota, y esta, pasa a modo edición
2. El usuario puede modificar el texto del título y/o de la nota en sí
3. Cuando haya acabado de editar, el usuario podrá hacer clic en un botón para confirmar la edición - [Prototipo](https://www.figma.com/file/IUGnIrSJ8RL1jdCuboNzWl/Avisa.me?node-id=74%3A264)
4. La aplicación hara un POST a /tasks/updateTask donde le pasaramos el id de la nota, el text actualicado y el título actualizado. Va a seguir siendo un formulario por el momento
5. El controlador debe actualizar el documento de mongoDB. Buscará entre todas los subdocumentos "tasks" de todos los workspaces buscando el identificador de la tarea. workspaceModel.tasks.findById(idTarea) <-- comprobar si esto es posible

### Modificar una Tarea estructuralmente puede entenderse en dos partes:
  1. La Captura y Envío mediante una petición HTTP desde el lado Cliente hacia el lado Servidor del Título y Texto de la Nota actualizados por el Usuario. 
  2. La Recepción en el endpoint de esos datos por parte de una función controladora que tomará estos datos y actualizará la base de datos haciendo el cambio persistente. 

 ### En detalle se ha implementado de la siguiente forma:

 1. El Usuario hace clic sobre el Título de la Nota y lo modifica, luego clic sobre el Texto de la Nota y lo modifica y por ultimo clic fuera de la Nota.
  
 2. Ante el registro del clic fuera del foco de la nota (_focusout_), el objeto Event invoca a una función de callback asignada para responder ante este _evento_. En este caso se ha agregado y definido como **onfocusout="onFocusUpdate(event)"**. Esta función se invocará solo ante un clic fuera de la nota. 
  
3. Dicha función en primer lugar solicitará los datos que requiere para funcionar:

   - **El id de la nota** : para saber qué nota queremos actualizar.  _Para obtenerlo se utiliza, de la propiedad **currentTarget** de Event,  la propiedad [dataset](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/dataset) la cual expone un mapa de todas aquellas atributos de tipo data- * ,  en este caso **data-id** . 
   - Las etiquetas `<p>` que delimitan tanto el contenido del Título y como del Texto tienen el atributo **data-id="<%=task._id%>"** por tanto para obtener el **task._id** la forma de recuperarlo fue utilizar **event.currentTarget.dataset.id;** y almacenarlo en una variable **idTask**._ 

    - **El título modificado**.  _Para obtenerlo utilizamos el id de la nota obtenido previamente y mediante querySelector requerimos su textContent **event.currentTarget.querySelector(`#task-title-${idTask}`).textContent;** y lo almacenamos es una variable **titleModified**_
 
    - **El texto modificado.** _Para obtenerlo utilizamos el id de la nota obtenido previamente y mediante querySelector requerimos su textContent **event.currentTarget.querySelector(`#task-title-${idTask}`).textContent;** y lo almacenamos es una variable **textModified**_
    - A fines prácticos todos estas variables se estructurarán en un sólo objeto **data** que almacenará mediante etiquetas homónimas las tres variables anteriores en una sola. 

  4. El objeto **data** contiene los datos actualizados que se requieren enviar mediante HTTP desde el cliente al servidor.
  
  5. Para esto se ha utilizado la [API de fetch()](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) , la cual es una función puesta globalmente a disponibilidad de Javascript por parte del Navegador que sirve para hacer peticiones HTTP desde el frontend a un endpoint (sin necesitar un formulario!), el cual en este caso es **'/tasks/updateTask'**, previamente definido. 
  - El primer argumento de fetch() es el endpoint al cual hará la petición.
  - El segundo argumento es un objeto que tendrá los siguietes campos:
     * El método que utilizará. En este caso POST por lo que incorpora a **data** en el body de la petición HTTP.
     * El campo body transportará el cuerpo del mensaje. Requiere un string JSON, por tanto **JSON.stringify(data)**
     * Por último en la cabecera de la petición es una buena práctica indicar el tipo de contenido que enviaremos.
        En este caso:  **'Content-Type': 'application/json'**
  - fetch() por defecto retorna una promesa. Para gestionar lo que sucede despues de que esa promesa se cumpla se ha utilizado el método **.then()** al cual se le enviará como parámetro una función anónima con la instrucción de realizar un informe por consola de los datos enviados. 

```
let response = fetch("/tasks/updateTaskColores", {
    method: "POST",
    body: JSON.stringify(data),
    headers: { 'Content-Type': 'application/json' }
  }).then( () => {
    console.log("response:", response);
    console.log("data:", data);
  })
};
```

6. Cuando el objeto **data** llega al endpoint "**/tasks/updateTask**" , la función **updateTask()** del controlador **taskControllers** se ocupa de recuperar mediante el método **body** (de Express.js) la información de **data** presente en el objeto **request**.

  ``` const { idTask, titleModified, textModified, reminderDate, reminderHour } = req.body; ```

7. En primer lugar se ha utilizado el **idTask** para buscar por Id (método **findById** de Mongoose) mediante el modelo **taskModel** la Tarea a la cual la petición HTTP que ingresa desde el Cliente hace referencia.

` const task = await taskModel.findById(idTask);`

8.  Mediante async y await se espera a que la Tarea sea encontrada  para luego actualizar los campos Title y Text y por último guardarlos persistentemente en la base de datos MongoDB. 

`await task.save();`

### Modificar título

1. Hacer click sobre el título. El usuario puede empezar a editar el texto.
2. El usuario edita el texto a su conveniencia. Debería cambiarse el texto.
3. El usuario hace click fuera de la nota. Los cambios se hacen persistentes.
4. Si recarga el workspace verá la nota con los cambios persistentes.

### Modificar cuerpo de la nota

1. Hacer click sobre el cuerpo de la nota. El usuario puede empezar a editar el texto.
2. El usuario edita el texto a su conveniencia. Debería cambiarse el texto.
3. El usuario hace click fuera de la nota. Los cambios se hacen persistentes.
4. Si recarga el workspace verá la nota con los cambios persistentes.

**Comment by Arnau-Mas** [comment]
Probando comentario

**Comment by Arnau-Mas** [comment]
- [ ] Probando

**Comment by Arnau-Mas** [comment]
- [ ] Prueba

- [ ] aa

- [ ] aa

**Comment by ignaciospadavecchia** [comment]
Hemos testeado la funcionalidad y se encuentra completamente operativa y tal como fue requerida. Doy por finalizada esta Issue.
