### ISSUE TITLE
Configurar aplicación - Ocultar tareas completadas

### ISSUE THREAD

**Issue by omiras** [FOAP-Netmind-2021/avisa-me#7]
# Objetivo 

El usuario debe poder configurar algunas _settings_ de la aplicación

1. El usuario dispone de un control que, si lo marca, ocultará las tareas marcadas como completadas de la lista tareas
2. El control aparecerá al acceder a /settings/:idWorkspace. Crear una vista simple para ello. El control puede ser un Select o un Checkbox. Usar los partials!! A la vista le podemos llamar settings.ejs.
3. En el momento que el usuario activa/desactiva la opción, debe recagarse la lista de tareas, y a partir de ahora, no 
deben mostrarse las tareas completadas
4. Las settings deberian guardarse en el Workspace. Modificar el modelo con un nuevo campo. (settings). El campo va a ser de tipo Object. El nombre de esta setting especifica podria ser "hideCompletedTasks".
5. Modificar la vista. Si workspace.settings.hideCompletedTasks es "true"; no debería mostrar las tareas completadas

### Crear nuevo Workspace con notas completadas

1. Ir al endpoint http://localhost:3000. Se renderiza una vista en la cual debe verse una casilla donde el usuario puede escribir una nueva nota.
2. Crear nuevas notas. El usuario escribe el título y/o texto de la nota. (Repetir el proceso varias veces)
3. Marcar notas como completadas. El usuario presiona el botón de marcar nota como completada (tik azul) y la nota se coloca en la parte inferior de las tareas y pasa a color gris.

### Configurar las Settings

1. Ir al endpoint http://localhost:3000/settings/:idWorkspace (escribir /settings manualmente en la URL). Se renderiza una vista en la cual hay la casilla de settings "Ocultar tareas completadas" con un checkbox.
2. El usuario marca la opción de "Ocultar tareas completadas". El usuario hace click en el checkbox de "Ocultar tareas completadas" y la casilla de checkbox queda marcada.
3. Volver al endpoint http://localhost:3000/:idWorkspace. Se ven únicamente las tareas NO completadas, las tareas que estaban de color gris, ahora no se ven.
4. Volver al endpoint http://localhost:3000/settings/:idWorkspace. La casilla de checkbox sigue marcada.
5. El usuario desmarca la opción de "Ocultar tareas completadas". El usuario hace click en el checkbox de "Ocultar tareas completadas" y la casilla de checkbox queda desmarcada.
6. Volver al endpoint http://localhost:3000/:idWorkspace. Se ven todas las tareas (completadas y sin completar).

**Comment by Arnau-Mas** [comment]
### Pseudocodigo Issue 7

* ~~Crear la vista settings~~
* ~~Usar los partials~~
* ~~Modificar el schema~~
* ~~Crear el endpoint /settings/:idWorkspace~~
* ~~añadir el select/checkbox~~
* ~~Crear el post del select/checkbox~~
* ~~Crear ruta y controller de Settings~~
* ~~Crear carpeta js dentro de public~~
* ~~Crear fichero settings.js para el script de la vista~~
* ~~Crear el objeto de settings en el schema de Workspace~~
* ~~al clicar, actualizar workspace con un parametro del tipo boolean i renderizar la vista actualizada
indicando si las tareas completadas aparecen o no~~
* ~~configurar la vista para que se renderice con la setting de hideCompletedTasks actualizada~~
* ~~Crear subschema de settings~~
* ~~Redactar los pasos para probar la issue~~
* Hacer test E2E
* Buscar animaciones en biblioteca AOS para ocultar tareas

**Comment by Arnau-Mas** [comment]
### Añadidos y posibles añadidos
6. La vista tiene que renderizar el estado actual de las settings
*Crear el endpoint de /settings sin ID o dejarlo con el error 404?*

**Comment by omiras** [comment]
Idea Test e2e:

1. Voy a http://localhost:3000
2. Creo un nuevo workspace añadiendo una tarea
3. Creo una segunda tarea
4. Voy a la pagina de settings
5. Activo "Ocultar tareas completadas"
6. Vuelvo a http://localhost:3000/:idWorkspace
7. Marco la primera tarea como completada
8. Verifico que la tarea ya no es visible en el DOM

**Comment by josecastp** [comment]
Se ha testeado la issue. Funcionan correctamente todos los pasos.

**Comment by josecastp** [comment]
Se ha testeado la issue de nuevo y **funcionan correctamente todos los pasos.**
Cierro la issue

**Comment by josecastp** [comment]
Se ha testeado la issue y **funcionan correctamente todos los pasos.**
Cierro la issue
